# Generated by Django 6.0 on 2026-02-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corepro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "code"],
            },
        ),
        migrations.CreateModel(
            name="SolarYearData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_label", models.CharField(max_length=7)),
                ("target", models.PositiveIntegerField(default=0)),
                ("booking", models.PositiveIntegerField(default=0)),
                ("installed", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_year_data",
                        to="corepro.district",
                    ),
                ),
            ],
            options={
                "ordering": ["year_label", "district__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("district", "year_label"),
                        name="unique_district_year_solar_data",
                    )
                ],
            },
        ),
    ]
