# Generated by Django 6.0.1 on 2026-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_email_otp_userprofile_email_verified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="otp_created_at",
            new_name="email_otp_created_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile_otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
